language: node_js
node_js:
  - '12'

branches:
  only:
  - blog-src

before_install:
- git config --global user.name "lzhxwmr"
- git config --global user.email "lzhxwmr@gmail.com"
- sed -i'' "s~git@github.com:lzhxwmr/blog.github.io.git~https://${ACCESS_TOKEN}@github.com/lzhxwmr/blog.github.io.git~" _config.yml
- cat ${ACCESS_TOKEN}

install:
- npm install hexo-cli -g
- npm install

script:
- npm run deploy