language: node_js
node_js:
  - '12'

branches:
  only:
  - blog-src

before_install:
- git config --global user.name "lzhxwmr"
- git config --global user.email "lzhxwmr@gmail.com"
- sed -i'' "s~https://github.com/lzhxwmr/blog.github.io.git~https://14ef60f43f064539e2155dd899d1e95231b7772b@github.com/lzhxwmr/blog.github.io.git~" _config.yml

install:
- npm install hexo-cli -g
- npm install

script:
- npm run deploy